name = "Democratic North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fc5d1437f70278b68870d7c7fa67b0f2f4d18a1a2ab17f24cb11691c551930"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
