name = "Democratic North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2c8134ef3c3a2971eace0e054889d089d85fb9fc8fae280dc444fbb4580b72"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
