name = "Democratic North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b5cea2e4ddab0bb7852df55774c76a041cc57a182ec2353d10f56427a825ae6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
