name = "Democratic North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2c5ec473b862bdc7a5ffc666ba7f5f9bf2e74077fc2b7dd2eb0d3a3371b2e80"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
